### PR TITLE
[JENKINS-63931] change section to advanced tag for ExtendedChoiceParameterDefinition

### PR DESCRIPTION
**Pull request by mageSFC2020**
[JENKINS-63931] change section to advanced tag for ExtendedChoiceParameterDefinition

try to  fixup jenkins job configure section shows unnecessary tabs

### CODE REVIEW

**Comment by mmh891113** [comment]
@vimil 

hi vimil  can you help me to review this PR?
I didn't find a better one to replace `<f:section>` Do you have any good suggestions?

**Comment by vimil** [comment]
Hi @mageSFC2020  could you shate a screenshot

**Comment by mageSFC2020** [comment]
QQ拼音截图20201103071654

**Comment by vimil** [comment]
@mageSFC2020  the screnshot looks good to me. I have merged the PR

**Pull request merged**
