### PR TITLE
Migrate docs

### PR DESCRIPTION
**Pull request by proxxz**

### CODE REVIEW

**Comment by bthompson0** [comment]
@oleg-nenashev can you review this when you get time please?

**Comment by bthompson0** [comment]
Sorry I opened this PR and let it sit.  I'm going to read the documentation on how to kick off another build.

**Comment by bthompson0** [comment]
I'm also beginning the process of converting the markdown to asciidoc so this isn't complete yet.  Shouldn't take long.

**Comment by bthompson0** [comment]
Alright, this one is ready to go.

**Comment by proxxz** [comment]
@vimil Could you review this when you get time, please?

**Pull request merged**
