### PR TITLE
Remove embeded jquery and use jquery plugin 

### PR DESCRIPTION
**Pull request by pascalmartin**
Remove embeded jquery and use jquery plugin  to avoid big memory leak in Delivery Pipeline View

Try this step to reproduce the memory leak:

Reproduce step

1- Install clean Jenkins ver. 1.625.1
2- Install all plugin update
3- Install pluging 
    "Job DSL", 
    "Build Pipeline Plugin",
    "Delivery Pipeline Plugin",
    "Groovy"    
4- Create new FreeStyle Job with name "Seed" and this step :
   *** Add Build Step for Process Job DSLs with this dsl script ***
```
// Start dsl script
def stages = ['Commit', 'Acceptance', 'Testing', 'Staging', 'Production']
def JOB_BY_STAGE = 5
def jobCount = 0
for(stage in stages)
{
    for (i = 0; i < JOB_BY_STAGE; i++) 
    {
        jobCount++
        def jobName = "Job" + jobCount
        def nextJobName = "Job" + (jobCount + 1)
        freeStyleJob(jobName) 
        {
            deliveryPipelineConfiguration(stage, jobName)
            steps {
                //systemGroovyCommand("println 'Hello world'")
                
                if (jobCount < (JOB_BY_STAGE * stages.size())){ 
                    downstreamParameterized {
                        trigger(nextJobName, 'UNSTABLE_OR_BETTER') {
                        }
                    }
                }
            }            
        }
    }
}
deliveryPipelineView("TestLeak DeliveryPipelineView") {
    pipelineInstances(50)
    enableManualTriggers()
    showAggregatedPipeline()
    showChangeLog()
    showDescription()
    showPromotions()
    allowPipelineStart()
    allowRebuild()
    pipelines {
        component("Job pipeline", "Job1")
    }
}
// End dsl script
```   
   *** Add system Groovy script build step after dsl step ***
```
// Start groovy script
def project = jenkins.model.Jenkins.instance.getItem("Job1")
def TARGET_PIPELINE_NUMBER = 50
for (i = 0; i < TARGET_PIPELINE_NUMBER; i++) 
{
    println "Starting pipeline " + (i + 1) + " / " + TARGET_PIPELINE_NUMBER
    def future = project.scheduleBuild2(0)
    def anotherBuild = future.waitForStart()
}  
// End groovy script   
```   
5- Set waiting period to 0 "http://localhost:8080/configure" and executor number to 5
6- Run seed job
7- Go "TestLeak DeliveryPipelineView" View and see no leak
8- Install "extended-choice-parameter-plugin" and see big browser memory leak

### CODE REVIEW

**Comment by pascalmartin** [comment]
Is is also possible to include the js in header.jelly only if the plugin should be displayed?

**Comment by pascalmartin** [comment]
Does the merge is considered

**Comment by dalvizu** [comment]
+1! came to this plugin looking to patch exactly this, good job @pascalmartin !

**Comment by oleg-nenashev** [comment]
:+1: , but needs an integration with the master branch

**Pull request merged**
