### PR TITLE
[JENKINS-32188] - Added DataBoundConstructor Annotation

### PR DESCRIPTION
**Pull request by issc29**
Added DataBoundConstructor Annotation to allow it to be compatible with
workflow plugin. See [JENKINS-32188](https://issues.jenkins-ci.org/browse/JENKINS-32188)

@reviewbybees

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
Isaac, could you please add the displayName to your GitHub account? :D

**Comment by oleg-nenashev** [comment]
DescriptorImpl::newInstance() has an additional logic, so most likely this change is not enough.
I'm also aware that this annotation causes regressions in other job types.

IMHO it's rather an issue in Jenkins Workflow, which does not support one of Jenkins **non-deprecated**  item instantination approach.

**Comment by issc29** [comment]
@oleg-nenashev It looks like DescriptorImpl::newInstance() just gets the JSON data and sets the parameters for the constructor. It is needed with the UI because you have choices (i.e. you can select "Basic Parameter Type" or "Multi-level Parameter type") of what to select, but there was still a possibility of filling out all the textboxes. So in order to only use the textboxes that are applicate to the choice you made, DescriptorImpl::newInstance() only sets the parameters required based on your selection. But in workflow since we are using the constructor directly we can set exactly which parameters should be set, so that should not be an issue.

Agreed! we should probably create a JIRA so that Jenkins Workflow supports this instantiation approach. In the meantime, can we do the reverse ;)

Interesting, so you are saying that DataBoundContructor may cause issues with other job types not Freestyle?

**Comment by oleg-nenashev** [comment]
> So in order to only use the textboxes that are applicate to the choice you made, DescriptorImpl::newInstance() only sets the parameters required based on your selection.

From what I see it causes particular issues with the default values processing. newInstance() performs the initialization on empty strings internally, hence this behavior won't be retained in Workflow from what I see

> Interesting, so you are saying that DataBoundContructor may cause issues with other job types not Freestyle?

It depends on the implementation. IIRC it should not impact pure-Stapler implementations (CC @jglick )

**Comment by jglick** [comment]
Not at a laptop and so cannot really help, but from looking at the diff this is clearly wrong.

Read the plugin dev guide section for Workflow on properly handling parameter defaults.

**Comment by oleg-nenashev** [comment]
I'm back from the vacation, so now I can put a :bug: for the defaults processing

**Pull request closed without merging**
