### PR TITLE
[JENKINS-27013] Added support for the Jenkins credentials plugin

### PR DESCRIPTION
**Pull request by jamesggraf**
This PR adds support for the Jenkins credentials plugin

### CODE REVIEW

**Comment by jamesggraf** [comment]
@vimil  Please review this when you get a chance

**Comment by oleg-nenashev** [comment]
@jamesggraf 
The PR does nothing if I understand correctly.
You just inject the mandatory dependency to the plugin, but don't use it in your code. What do you try to achieve?

**Comment by jamesggraf** [comment]
@oleg-nenashev In order to utilize classes from the credentials plugin in my Groovy scripts, I needed to add this dependency. I was going to bundle this with this change: https://github.com/jenkinsci/extended-choice-parameter-plugin/pull/13 but I decided to separate this out since the groovy/classloading change in PR #13 can be merged separately from this

**Comment by oleg-nenashev** [comment]
> In order to utilize classes from the credentials plugin in my Groovy scripts

Just install Groovy/Credentials plugins to your installation.
There's no need to add plugin dependencies if you use plugins in your personal scripts

**Comment by jamesggraf** [comment]
@oleg-nenashev Again, this change only makes sense in the context of PR #13

**Comment by jamesggraf** [comment]
@oleg-nenashev And of course, I am open to suggestions on how to handle PR #13 without changing the plugin class loading strategy

**Comment by KostyaSha** [comment]
:-1:  if you need any plugin to be available in jenkins - then install it in your jenkins.

**Pull request closed without merging**
