### PR TITLE
[JENKINS-71661] jsoneditor.js overwrites standard CustomEvent JS function

### PR DESCRIPTION
**Pull request by jgreffe**
https://issues.jenkins.io/browse/JENKINS-71661

Condition of `CustomEvent` existence before defining it.

### Testing done

Tested with some simple extended choice parameters,
with the condition, the `CustomEvent` isn't redefined (standard one is used), and the parameters are correctly displayed:
Monosnap Jenkins 2023-07-17 15-43-25

`jsoneditor.min.js` diff:
Monosnap History: jsoneditor min js 2023-07-17 16-00-35

```[tasklist]
### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

### CODE REVIEW

**Comment by batmat** [comment]
@chonton thanks! Could you please release a version? 
I see Incrementals is enabled, but not a full-blown or a CD release. Thanks!

**Comment by batmat** [comment]
My bad, I had missed that this plugin had CD enabled.

**Comment by batmat** [comment]
Erm, actually, the CD release was skipped because this PR had no "interesting" label. And it failed when retriggered... :thinking:

**Comment by chonton** [comment]
I released manually. Try again.

**Comment by batmat** [comment]
Awesome thanks! I do see the version `375.v72e4b_a_d33d33` from https://plugins.jenkins.io/extended-choice-parameter/ and from Jenkins, but I do not see the tag here. 

Maybe you didn't push the new tag to the repo here yet? Thank you

**Pull request merged**
