### PR TITLE
[WiP] - Store values from multi-level multi select list

### PR DESCRIPTION
**Pull request by lkisac**
I added a feature to store multiple values for the multi level select list.

It stores each selection and returns a string.  This is an example with 3 levels for the multi select list:
{1:dropdown1value,dropdown2value,dropdown3value:2:dropdown1value,dropdown2value,dropdown3value:3:dropdown1value,dropdown2value,dropdown3value:}  etc.

The Extended Choice Parameter field's name holds the string value.
Example (Jenkins Shell script):
  echo ${Multi_Level_List}

I have a perl script that parses this string and build a hash containing all multi select values.  

sub ParseMultiLevelString {
	my $multiLevelString = shift;  
	my %hash;
	my $eachMulti = 1; # i.e. { => 1:dropdownval1....} 

	my ( $dropdown1header, $dropdown2header, $dropdown3header ) = ( "", "", "" );

	while ( $multiLevelString =~ m/[$eachMulti]{1}:([^:]+),([^:]+),([^:]+):[0-9\}]{1}/ ) {
           # store into hash
		$hash{$eachMulti}{'dropdownOne'}     = $1;
		$hash{$eachMulti}{'dropdownTwo'}     = $2;
		$hash{$eachMulti}{'dropdownThree'}  = $3;

		$eachHost++;
        }
	return ( \%buildSetupHash, $eachHost );
}

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
It's hard to review changes due to the multiple formatting changes.
Move them to a separate commit at least

**Comment by lkisac** [comment]
This commit shows the changes from the original without all the formatted lines
https://github.com/lkisac/extended-choice-parameter-plugin/commit/84c44d0a288546a971a708f32dbb3800de1ce5b7

**Comment by oleg-nenashev** [comment]
I'm not skilled enough in JavaScript to review the code, but the entire Java part should be reworked

**Comment by lkisac** [comment]
Thanks for the clear feedback.  Based off your review, I made the necessary changes.  The initial extension I did was a quick fix so we could use it right away and I noticed other people also inquiring about how to store all values from the multi-level select list.  

One thing I was unable to get working was the logger (java.util.logger.Logger), it doesn't seem to be displaying in the console as System IO was.  Since it's only for debugging purposes, I have another commit without the debugging lines.

I've been using this modified plugin for several months and it's been working well so far with the various plugins on our Jenkins instance.

**Comment by oleg-nenashev** [comment]
@lkisac 
* The concurrency issue for <code>multiLevelColumns</code>, <code>allCols</code>  and <code>strValue</code> has not been solved
* There should be only one <code>DataBoundConstructor</code>. I'm not sure if you use the proper one
* IMO such detailed logging is not required, but it's up to the plugin's owner

I would recommend to merge you commits into a single one in order to review the code again.
Unit tests for the feature would be useful as well.

**Comment by lkisac** [comment]
Sorry, ignore the last push.  I'm going to move everything to a separate branch.  Once I'm finished I'll merge the commits into one and push it to master.

**Comment by lkisac** [comment]
I created a new branch from master before the changes I did (91339d65f064c21472f4402be4a892c78a9bd4d6).  I edited the files and I was going to use squash or rebase to merge commits into one, doing something like `git reset --soft HEAD~7` but instead I used `git reset --hard 91339d65f064c21472f4402be4a892c78a9bd4d6` to remove those commits and merge that latest branch, but didn't realize it would close this pull request.  I do have my latest commit showing in my master, so I'm not sure why it won't appear here and run the test.

Should I open a new pull request?

I don't have Unit Tests written yet, I'm still getting acquainted with JUnit and HTMLUnit.  However, I tried various scenarios with the plugin on my local Jenkins and found an issue with the way the values were being stored, which I've fixed.

The addition I made is fairly simple, so I don't think it should break anything else, but I have another branch where I'll work on Unit Tests for this.

**Comment by oleg-nenashev** [comment]
@lkisac 
IMO It's hard to break the plugin in the scope of the architecture. The current version really demands a re-work.

> Should I open a new pull request?

Force push should resolve any issue

**Comment by lkisac** [comment]
It says everything is up-to-date.

This is my latest commit b7a5a76b9cfec71cd127c92c5d15b9c0911e26ce, but it's not showing here for me to click the 'Reopen and comment' button.

**Comment by lkisac** [comment]
I read that it's not possible to re-open a [merged pull request](http://stackoverflow.com/questions/12674304/github-reopening-a-merged-pull-request).  

Would it be ok to go ahead and open a new pull request?

**Comment by oleg-nenashev** [comment]
Your PR has not been merged. You just closed it.

BTW feel free to open a new one if it is more convenient for you. Just don't forget to reference this PR

**Comment by lkisac** [comment]
Ah right, the PR has not been merged to jenkinsci-master yet, no. I was thinking of my merge from [branch](https://github.com/lkisac/extended-choice-parameter-plugin/tree/len-storeMultipleValues1) to [lkisac-master](https://github.com/lkisac/extended-choice-parameter-plugin/tree/master).  

Unfortunately it's not showing that merge here as it was during my previous commits.  I think the `git reset --hard 91339d65f064c21472f4402be4a892c78a9bd4d6` I did to delete those old commits closed the PR and now it won't recognize any new commits after being closed.  `git reset --soft` or `git squash` might've been better to use.

At any rate, I guess it would be easier to open a new one and reference this PR.  
I'll go ahead and do that.  Thanks.

**Comment by lkisac** [comment]
@oleg-nenashev
Question:  Is the change I made considered a simple 'hot-fix' and if so, should I leave the name out of the Copyright section at the top of the code, and pom.xml `<developers>`?   

I made another commit without my name in the copyright.  It's not appearing in the new [PR](https://github.com/jenkinsci/extended-choice-parameter-plugin/pull/10), but it is [here](https://github.com/lkisac/extended-choice-parameter-plugin).  What would be considered a more significant change to include the name there? (if this change is not)

**Pull request closed without merging**
