### PR TITLE
[JENKINS-27011] Exceptions are logged in ExtendedChoiceParameterDefiniti...

### PR DESCRIPTION
**Pull request by jamesggraf**
[JENKINS-27011] Exceptions are logged in ExtendedChoiceParameterDefinition.java

### CODE REVIEW

**Comment by jamesggraf** [comment]
@vimil Please review this when you get a chance

**Comment by oleg-nenashev** [comment]
LGTM

**Comment by oleg-nenashev** [comment]
Actually, you still suppress stacktraces from exceptions. Probably, it's "as designed" due to the risk of log overload if the issue happens

**Comment by jamesggraf** [comment]
@oleg-nenashev It's generally bad policy to swallow exceptions like this because it makes debugging your groovy scripts much more difficult in the event of an exception

**Comment by vimil** [comment]
Present in latest release

**Pull request closed without merging**
